name: build

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ steps.buildx.outputs.platforms }}
          push: true
          tags: localhost:5000/name/app:latest
          build-args: |
            BUILD_DATE=${date -u +"%Y-%m-%dT%H:%M:%SZ"}
            VCS_REF=${GITHUB_SHA::8}

      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/name/app:latest
